version: "3.7"

volumes:
  kong_data: {}

networks:
  kong-net:
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16

services:
  dico:
    build:
      context: ./dico
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    networks:
      kong-net:
        ipv4_address: 172.31.0.4
    entrypoint: ["java","-jar","app.jar"]
    environment:
      NODE_ENV: compose
  
  demo:
    build:
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    networks:
      kong-net:
        ipv4_address: 172.31.0.3
    entrypoint: ["java","-jar","app.jar"]
    environment:
      NODE_ENV: compose
    
  kong-migrations:
    image: kong
    command: kong migrations bootstrap
    networks:
      - kong-net
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong-migrations-up:
    image: kong
    command: kong migrations up && kong migrations finish
    depends_on:
      - db
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong:
    image: kong
    user: kong
    depends_on:
      - db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_USER: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PG_PASSWORD: kong
    ports:
      - "127.0.0.1:8001:8001/tcp"
      - "8000:8000"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    networks:
      kong-net:
        ipv4_address: 172.31.0.10
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  konga-prepare:
    image: pantsel/konga:next
    networks:
      - kong-net
    command: "-c prepare -a postgres -u postgresql://kong:kong@db:5432/konga"
    restart: on-failure
    depends_on:
      - db

  konga:
    image: pantsel/konga:next
    restart: always
    networks:
      kong-net:
        ipv4_address: 172.31.0.11
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgresql://kong:kong@db:5432/konga
      DB_DATABASE: konga
      NODE_ENV: production
    depends_on:
      - db
    ports:
      - "1337:1337"

  db:
    image: postgres:9.5
    environment:
      POSTGRES_MULTIPLE_DATABASES: kong,konga
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    healthcheck:
      test: ["CMD", "pg_isready -U kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    networks:
      kong-net:
        ipv4_address: 172.31.0.5
    tty: true
    volumes:
      - kong_data:/var/lib/postgresql/data



