version: "3.7"

volumes:
  kong_data: {}

networks:
  kong-net:
    ipam:
      driver: host

services:    
  kong-migrations:
    image: kong
    command: kong migrations bootstrap
    networks:
      - host
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong-migrations-up:
    image: kong
    command: kong migrations up && kong migrations finish
    depends_on:
      - db
    networks:
      - host
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong:
    image: kong
    user: kong
    depends_on:
      - db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_USER: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PG_PASSWORD: kong
    ports:
      - "127.0.0.1:8001:8001/tcp"
      - "8000:8000"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    networks: 
      - host
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:9.5
    environment:
      POSTGRES_MULTIPLE_DATABASES: kong,konga
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    healthcheck:
      test: ["CMD", "pg_isready -U kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    networks: 
      - host
    tty: true
    volumes:
      - kong_data:/var/lib/postgresql/data



