version: "3.7"

volumes:
  kong_data: {}

networks:
  kong-net:
    ipam:
      driver: default

services:    
  kong-migrations:
    image: kong
    command: kong migrations bootstrap
    networks:
      - kong-net
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong-migrations-up:
    image: kong
    command: kong migrations up && kong migrations finish
    depends_on:
      - db
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:9.5
    environment:
      POSTGRES_MULTIPLE_DATABASES: kong,konga
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    expose:
      - "443"
    healthcheck:
      test: ["CMD", "pg_isready -U kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    networks:
      - kong-net
    tty: true
    volumes:
      - kong_data:/var/lib/postgresql/data



